Algoritmo "Prestacao"
//  
//  

Var
preco, prest1, prest2, prest3, prest4, prest5: real
Inicio
escreval("Informe um preço em R$: ")
leia(preco)

prest1 <- preco / 1
prest2 <- preco / 2
prest3 <- preco / 3
prest4 <- preco / 4
prest5 <- preco / 5

escreval("Prestação 1: R$",prest1:2:2)
escreval("Prestação 2: R$",prest2:2:2)
escreval("Prestação 3: R$",prest3:2:2)
escreval("Prestação 4: R$",prest4:2:2)
escreval("Prestação 5: R$",prest5:2:2)

Fimalgoritmo